[package]
name = "redis-exploit"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
futures = "0.3.28"
ipnetwork = "0.20.0"
redis = "0.23.0"
tokio = { version = "1.28.1", features = ["full"] }
